spring:
  application.name: thumb-backend
  mvc:
    servlet:
      path: /api
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thumb
    username: root
    password: 12345678
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
knife4j:
  enable: true
  setting:
    language: zh_cn
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/generator/mapper/*.xml